on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: shekhar.azurecr.io
        username: ${{ secrets.acr_shekhar_username }}
        password: ${{ secrets.acr_shekhar_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t shekhar.azurecr.io/shekhardockerk8scluster:${{ github.sha }}
        docker push shekhar.azurecr.io/shekhardockerk8scluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_shekhardockerk8scluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep shekhardockerk8sclusterd703 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace shekhardockerk8sclusterd703`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: shekhardockerk8sclusterd703
        container-registry-url: shekhar.azurecr.io
        container-registry-username: ${{ secrets.acr_shekhar_username }}
        container-registry-password: ${{ secrets.acr_shekhar_password }}
        secret-name: shekhardockedockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: shekhardockerk8sclusterd703
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          shekhar.azurecr.io/shekhardockerk8scluster:${{ github.sha }}
        imagepullsecrets: |
          shekhardockedockerauth