on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: raterias.azurecr.io
        username: ${{ secrets.acr_raterias_username }}
        password: ${{ secrets.acr_raterias_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t raterias.azurecr.io/shekhardockerk8scluster:${{ github.sha }}
        docker push raterias.azurecr.io/shekhardockerk8scluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_shekhardockerk8scluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep shekhardockerk8sclustere331 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace shekhardockerk8sclustere331`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: shekhardockerk8sclustere331
        container-registry-url: raterias.azurecr.io
        container-registry-username: ${{ secrets.acr_raterias_username }}
        container-registry-password: ${{ secrets.acr_raterias_password }}
        secret-name: shekhardockedockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: shekhardockerk8sclustere331
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          raterias.azurecr.io/shekhardockerk8scluster:${{ github.sha }}
        imagepullsecrets: |
          shekhardockedockerauth